In [7]:
import tensorflow as tf
import numpy as np

# Task 1.1: Create a TensorFlow tensor with random float values and compute sum, mean, max
tensor = tf.random.uniform(shape=(5, 5), minval=1, maxval=20, dtype=tf.float32)
sum_tensor = tf.reduce_sum(tensor)
mean_tensor = tf.reduce_mean(tensor)
max_tensor = tf.reduce_max(tensor)

print("Tensor:", tensor.numpy())
print("Sum:", sum_tensor.numpy())
print("Mean:", mean_tensor.numpy())
print("Max:", max_tensor.numpy())

# Task 1.2: Create a 3D TensorFlow tensor and access specific elements
tensor_3d = tf.random.uniform(shape=(3, 3, 3), minval=1, maxval=20, dtype=tf.float32)
print("3D Tensor:", tensor_3d.numpy())
print("Specific Element (1,1,1):", tensor_3d.numpy()[1, 1, 1])
print("2D Slice:", tensor_3d.numpy()[1, :, :])
print("1D Slice:", tensor_3d.numpy()[1, 1, :])

Tensor: [[ 9.247681   1.8706456 18.105057   8.396138  11.45101  ]
 [16.947342  15.848382  18.719984   7.328684  11.448613 ]
 [17.26648    3.1537142  7.258832  16.786196  13.909014 ]
 [ 6.062689   2.1527667 14.045347   8.45727   12.795698 ]
 [12.290527  18.275225   7.926074  19.677822  18.503042 ]]
Sum: 297.92426
Mean: 11.91697
Max: 19.677822
3D Tensor: [[[12.717478   9.4507475  8.395277 ]
  [ 6.2855515 10.429748  19.383698 ]
  [13.286725   4.872589  17.02681  ]]

 [[ 2.1010027 19.98514   15.350741 ]
  [ 8.380186  19.285057   6.12648  ]
  [ 3.247065   1.8579595 13.500707 ]]

 [[13.325823   9.756042  18.78207  ]
  [ 1.2866532  9.406218   2.566707 ]
  [15.630391   3.2925322 12.555785 ]]]
Specific Element (1,1,1): 19.285057
2D Slice: [[ 2.1010027 19.98514   15.350741 ]
 [ 8.380186  19.285057   6.12648  ]
 [ 3.247065   1.8579595 13.500707 ]]
1D Slice: [ 8.380186 19.285057  6.12648 ]


In [5]:
# Task 2: Function for tensor operations
def tensor_operations(tensor1, tensor2):
    tensor1 = tf.constant(tensor1, dtype=tf.float32)
    tensor2 = tf.constant(tensor2, dtype=tf.float32)
    return {
        "addition": tf.add(tensor1, tensor2).numpy(),
        "subtraction": tf.subtract(tensor1, tensor2).numpy(),
        "multiplication": tf.multiply(tensor1, tensor2).numpy(),
        "division": tf.divide(tensor1, tensor2).numpy()
    }

tensor1 = [10, 20, 30]
tensor2 = [5, 10, 15]
result = tensor_operations(tensor1, tensor2)

print("Addition:\n", result["addition"])
print("Subtraction:\n", result["subtraction"])
print("Multiplication:\n", result["multiplication"])
print("Division:\n", result["division"])

Addition:
 [15. 30. 45.]
Subtraction:
 [ 5. 10. 15.]
Multiplication:
 [ 50. 200. 450.]
Division:
 [2. 2. 2.]


In [6]:
# Task 3.1: Create a NumPy array, sort in ascending and descending order
array = np.random.rand(10)
ascending_sorted = np.sort(array)
descending_sorted = np.sort(array)[::-1]
print("Original Array:", array)
print("Ascending Sorted:", ascending_sorted)
print("Descending Sorted:", descending_sorted)

# Task 3.2: Create a 2x2 NumPy matrix, compute transpose and inverse
matrix = np.random.rand(2, 2)
transpose = np.transpose(matrix)
inverse = np.linalg.inv(matrix)
print("Matrix:", matrix)
print("Transpose:", transpose)
print("Inverse:", inverse)

# Task 3.3: Create a 2D NumPy array, compute row sum, column mean, and standard deviation
matrix_2d = np.random.rand(3, 3)
row_sums = np.sum(matrix_2d, axis=1)
column_means = np.mean(matrix_2d, axis=0)
std_dev = np.std(matrix_2d)
print("2D Array:", matrix_2d)
print("Row Sums:", row_sums)
print("Column Means:", column_means)
print("Standard Deviation:", std_dev)


Original Array: [0.59682914 0.03656609 0.12803917 0.01391931 0.92901524 0.94336706
 0.85225699 0.13040493 0.84990417 0.49436239]
Ascending Sorted: [0.01391931 0.03656609 0.12803917 0.13040493 0.49436239 0.59682914
 0.84990417 0.85225699 0.92901524 0.94336706]
Descending Sorted: [0.94336706 0.92901524 0.85225699 0.84990417 0.59682914 0.49436239
 0.13040493 0.12803917 0.03656609 0.01391931]
Matrix: [[0.17468714 0.81922558]
 [0.84639995 0.14800392]]
Transpose: [[0.17468714 0.84639995]
 [0.81922558 0.14800392]]
Inverse: [[-0.22171607  1.22723418]
 [ 1.26794252 -0.26168864]]
2D Array: [[0.31660846 0.08831326 0.85315129]
 [0.73738104 0.08759342 0.45909334]
 [0.09148457 0.84280088 0.12547879]]
Row Sums: [1.258073   1.2840678  1.05976424]
Column Means: [0.38182469 0.33956919 0.47924114]
Standard Deviation: 0.3146392277466911
